name: CI
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    #paths:
    #  - '**/pom.xml'
    #  - '**/src/**'
env:
  JAVA_VERSION: 11
jobs:
  tests:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./mvnw -B dependency:resolve dependency:resolve-plugins
      - run: ./mvnw clean test install -f reservation-service
      - run: ./mvnw clean test -f reservation-client
  dependency-updates:
    if: startsWith(github.event.inputs.trigger, 'm')
      || startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "Trigger: ${{ github.event.inputs.trigger }}"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./mvnw -B dependency:resolve dependency:resolve-plugins
      - run: ./mvnw versions:display-property-updates
